language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database testing_app_test;' -U postgres
script:
  - "bundle exec rspec spec"
  - "bundle exec rake jasmine:ci"
env:
  - PG_USERNAME='postgres'
