development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.class.parent_name %>_development
  pool: 5
  host: localhost
  username:  <%= ENV['PG_USERNAME'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.class.parent_name %>_test
  pool: 5
  host: localhost
  username: <%= ENV['PG_USERNAME'] %>
  password:
